### ISSUE TITLE
Confusion about averaging attention scores

### ISSUE THREAD

**Issue by TtuHamg** [sen-mao/SuppressEOT#4]
Hi, sen-mao. I think SupressEOT is an interesting work, thanks for your contribution. However, I am confused about the operation in which you divide `self.cur_step` for each attention score in `get_average_attention`. Can you explain why you do this?
![QQ_1725166113523](https://github.com/user-attachments/assets/76511df4-ecca-4449-a60c-52f6982b8672)

**Comment by sen-mao** [comment]
Hi, thank you for your interest in our work!

This operation follows the code from prompt-to-prompt (https://github.com/google/prompt-to-prompt/blob/main/prompt-to-prompt_stable.ipynb). Since the attention map is the sum of the attention maps from all previous steps, the final result needs to be divided by `self.cur_step` to obtain the final attention map.

![image](https://github.com/user-attachments/assets/fbe94e23-2fee-400d-b7f5-af8b026630d6)

**Comment by TtuHamg** [comment]
Thank you for your response, I understand now.
